---
- hosts: all

  vars:
    jenkins_home: /var/lib/jenkins

  tasks:

  - name: Download Jenkins Repository
    get_url:
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
    become: true

  - name: Import Jenkins Repository Key
    rpm_key:
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      state: present
    become: true
    
  - name: Install Jenkins
    yum:
      name: jenkins
      state: present
    become: true

  - name: Install Java
    yum:
      name: java
      state: present
    become: true

  - name: Start Jenkins
    systemd:
      name: jenkins
      state: started
    become: true

  - name: Check Jenkins installation
    wait_for:
      path: "{{ jenkins_home }}/secrets/master.key"
    become: true

  - name: Remove {{ jenkins_home }}/secrets/initialAdminPassword
    file:
      path: "{{ jenkins_home }}/secrets/initialAdminPassword"
      state: absent
    become: true

  - name: Set user and password admin/admin
    copy:
      src: config.xml
      dest: "{{ jenkins_home }}/users/admin"
    become: true
    notify:
      - Restart Jenkins

  handlers:
  - name: Restart Jenkins
    systemd:
      name: jenkins
      state: restarted
    become: true
